spring:
  application:
    name: aichat
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 60000
      jedis:
        pool:
          min-idle: 10
          max-idle: 50
          max-active: 200
          max-wait: -1
      password: "123456"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: "123qwe"
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall,log4j

server:
  port: 2323
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

chat:
  bailian:
    apiKey:
  qianfan:
    apiKey:
    secretKey:
  hunyuan:
    secretId:
    secretKey:
  spark:
    APIPassword:
  volcengine:
    apiKey:
  siliconflow:
    apiKey:
  deepSeek:
    apiKey: